### ISSUE TITLE
type hierarchy

### ISSUE THREAD

**Issue by martingartonft** [Financial-Times/neo-model-utils-go#3]
I wonder whether we should keep the type hierarchy (in terms of Neo4j Labels) in here too?

I see knowledge of the child/parent types spread around, and it might be better in here because not only would it avoid existing repetition, but it would also allow other logic in here to become simpler.

If people agree, I'll take a stab (it's only about 10 minutes of work) and see what people think.

**Comment by dgem** [comment]
Sounds like a good idea.
I've also got a few other candidates to put in here around neo and models, so will raise other issues so we can discuss...

**Comment by martingartonft** [comment]
cool. lets keep PR's small and independent as we go.

**Comment by dgem** [comment]
#5
